apiVersion: v1
kind: Service
metadata:
  name: multicluster-controlplane
  labels:
    component: multicluster-controlplane
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: multicluster-controlplane